# Generated by Django 4.2.3 on 2023-07-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='if_sold',
            new_name='is_sold',
        ),
    ]
