# Generated by Django 4.2.2 on 2023-08-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_rename_if_sold_item_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Category',
            new_name='category',
        ),
    ]
